Feat : create footer
mju-likelion/mormora pull request #1
Opened 2021-03-01 16:31 UTC by kimhan0421

create footer(pc, tablet, mobile)

2021-03-02 11:34 UTC, ndaemy commented on .eslintrc
> +    "jsx-a11y/anchor-is-valid": "off",
👍

2021-03-02 11:38 UTC, ndaemy requested changes

2021-03-02 11:38 UTC, ndaemy commented on pages/_app.tsx
> +      </footer>
여긴 이렇게 하는것보다 Footer컴퍼넌트 안의 SectionWrap을 footer로 만드는게 낫지
어차피 footer는 semantic tag니까

2021-03-02 11:38 UTC, ndaemy commented on components/common/Footer.tsx
> +        <SectionSnsStyle>
컴퍼넌트 안에서 전체 감싸는 component naming convention은 같이 한번 정해봅시다
Self를 쓸지 Wrap을 쓸지 Inner같은걸 쓸지

2021-03-03 14:12 UTC, kimhan0421 commented on pages/_app.tsx
> +      </footer>
semantic tag는 가시적으로 숨기는게 더 낫다는거지?

2021-03-03 14:12 UTC, kimhan0421 commented on components/common/Footer.tsx
> +        <SectionSnsStyle>
좋습니다. 언제 시간되실까요?

2021-03-06 09:43 UTC, ndaemy commented on components/common/Footer.tsx
> +    <SectionSelf>
이건 파일명이 Footer니까 FooterSelf 어때요?

2021-03-06 09:43 UTC, ndaemy commented on components/common/Footer.tsx
> +        <SectionSnsBlock>
Section이라는 단어는 그 자체로 "영역" 이라는 뜻을 담고 있어서, Block 혹은 Wrapper 이런 애들이랑 동의어로 많이 쓰여요
저런 식으로 쓰게 되면 의미가 조금 헷갈릴 수 있어서 다른 이름이면 어떨까? 합니다

2021-03-06 10:04 UTC, ndaemy commented on components/common/Footer.tsx
> +function Footer(): ReactElement {
리액트 component를 function 키워드로 만들때는 :ReactElement를 안써요
확장자 자체가 tsx라서 불필요하기도 하고, 무엇보다 React17 이후로 import 뭐시기 from 'react'; 가 불필요해졌는데 굳이 import 해야되거든요

2021-03-06 10:07 UTC, ndaemy requested changes

2021-03-06 10:07 UTC, ndaemy commented on components/common/Footer.tsx
> +  max-width: 1440px;
여기에 max-width로 걸어버리면 슬랙에서 얘기한 것처럼 화면이 확대될 때 좌우 여백이 footer 색상으로 차는게 아니라 background색상으로 차요 여기는 수정이 필요할듯

2021-03-06 15:06 UTC, kimhan0421 commented on components/common/Footer.tsx
> +function Footer(): ReactElement {
수정완료했습니당

2021-03-06 15:10 UTC, kimhan0421 commented on components/common/Footer.tsx
> +    <SectionSelf>
아하 넵!!

2021-03-06 15:17 UTC, kimhan0421 commented on components/common/Footer.tsx
> +        <SectionSnsBlock>
SnsBlock으로 변경했습니다!

2021-03-06 15:19 UTC, kimhan0421 commented on components/common/Footer.tsx
> +  max-width: 1440px;
수정했습니다!

2021-03-06 15:30 UTC, ndaemy requested changes

2021-03-06 15:30 UTC, ndaemy commented on components/common/Footer.tsx
> +        <SectionSnsWrap>
Section 지우세요

2021-03-06 15:30 UTC, ndaemy commented on components/common/Footer.tsx
> +            <SectionSnsLine />
여기도 Section

2021-03-06 15:30 UTC, ndaemy commented on components/common/Footer.tsx
> +                  height={19}
여기도 Section

2021-03-14 06:18 UTC, ndaemy commented on components/common/Footer.tsx
>    @media screen and (max-width: 768px) {
요거 말인데, screen and 는 굳이 안써도 돼

```
@media (max-width: 768px) { ... } 이래도 ㄱㅊ

2021-03-17 09:48 UTC, seunghwako commented on components/common/Footer.tsx
> +  max-width: 1440px;
max-width 주면 양옆 짤려보이는데 저만 그런가여??

2021-03-17 10:58 UTC, ndaemy commented on components/common/Footer.tsx
> +  max-width: 1440px;
아뇨 짤리는게 정상입니다 저거 수정해야돼요

2021-03-27 06:18 UTC, merged