회원가입 페이지 기본 틀
mju-likelion/mormora pull request #2
Opened 2021-03-06 16:22 UTC by seunghwako

코드리뷰 해주세요~

2021-03-14 13:57 UTC, ndaemy commented on .eslintrc
> +  ],
뭐야 이건 왜 바꼈어

2021-03-14 13:57 UTC, ndaemy commented on .eslintrc
> +}
요거는 말 나온김에 첨부하는거니까 ㅊㄱㅊㄱ
https://minz.dev/19

2021-03-14 13:57 UTC, ndaemy commented on package.json
> +}
전체적으로 다 이러네

2021-03-14 13:57 UTC, ndaemy commented on pages/signup.tsx
> +  font-family: Roboto;
이건 Roboto가 아닐텐데, 실수인듯

2021-03-14 13:57 UTC, ndaemy commented on pages/signup.tsx
> +  font-family: Noto Sans KR;
여기의 font-family는 GlobalStyles에서 한번 만들기 때문에, 굳이 다시 선언할 필요가 없어요

2021-03-14 13:57 UTC, ndaemy commented on pages/signup.tsx
> +  letter-spacing: 0em;
불필요한 css는 빼는것으로! 속도가 떨어집니다

2021-03-14 13:57 UTC, ndaemy commented on pages/signup.tsx
> +  background-color: #141517;
요건 내꺼 브랜치에서는 만들어둔 방법이 있는데, 공통으로 많이 쓰일만한 css 변수들은 theme으로 빼뒀어요
https://github.com/mju-likelion/mormora/blob/feature/signin/theme/index.ts 
나중에 엎어야 할듯

2021-03-14 13:57 UTC, ndaemy commented on pages/signup.tsx
> +  }
이건 나도 최근에 깨달은건데, cursor: pointer는 굳이 &:hover에 있을 필요가 없더라고
그냥 cursor: pointer; 해도 해당 컴퍼넌트에서는 pointer니까

2021-03-14 14:00 UTC, ndaemy requested changes

2021-03-14 14:00 UTC, ndaemy commented on package.json
> +    "@types/yup": "^0.29.11",
yup은 그 자체로 typescript를 지원하기 때문에 @types가 필요 없고,
@types/ 라이브러리들은 런타임에서 필요하지 않기 때문에 (transpiling 된 이후 즉 js니까)
devDependencies로 가는게 맞아요

2021-03-14 14:11 UTC, ndaemy requested changes

2021-03-14 14:11 UTC, ndaemy commented on pages/signup.tsx
> +  height: 48px;
이건 처음에 width랑 height를 안주면 굳이 text-align을 주지 않아도 가운데 정렬이 돼

2021-03-14 14:11 UTC, ndaemy commented on pages/signup.tsx
> +  font-style: normal;
font-style: normal은 굳이 안써도 돼 (괜히 css파일 한줄이 늘어나니까)

2021-03-14 14:11 UTC, ndaemy commented on pages/signup.tsx
> +  letter-spacing: 0em;
letter-spacing: 0em;도 안써도 돼

그리고 참고로 0은 단위를 안붙여도 돼

2021-03-15 01:18 UTC, seunghwako commented on .eslintrc
> +}
ㅊㄱㅊㄱ

2021-03-15 01:19 UTC, seunghwako commented on pages/signup.tsx
> +  font-family: Roboto;
global style에 있어서 삭제

2021-03-15 01:19 UTC, seunghwako commented on pages/signup.tsx
> +  letter-spacing: 0em;
확인!

2021-03-15 01:19 UTC, seunghwako commented on pages/signup.tsx
> +  background-color: #141517;
네네

2021-03-15 01:19 UTC, seunghwako commented on pages/signup.tsx
> +  }
변경

2021-03-15 01:19 UTC, seunghwako commented on package.json
> +    "@types/yup": "^0.29.11",
@types/yup 삭제

2021-03-15 01:19 UTC, seunghwako commented on pages/signup.tsx
> +  height: 48px;
해보니까 안먹혀요!

2021-03-15 01:19 UTC, seunghwako commented on pages/signup.tsx
> +  font-style: normal;
네네

2021-03-15 01:24 UTC, ndaemy commented on pages/signup.tsx
> +  height: 48px;
엥 내가 어제 해봤을땐 됐는데?!

2021-03-15 01:26 UTC, seunghwako commented on pages/signup.tsx
> +  height: 48px;
사실 여기에 어차피 로고 그림 들어갈거라서 상관없긴한데

2021-03-15 01:27 UTC, seunghwako commented on pages/signup.tsx
> +  height: 48px;
<img width="178" alt="스크린샷 2021-03-15 오전 10 26 54" src="https://user-images.githubusercontent.com/52697089/111092304-0668ca80-8579-11eb-84ae-eb92e660a8dc.png">
<img width="187" alt="스크린샷 2021-03-15 오전 10 27 01" src="https://user-images.githubusercontent.com/52697089/111092305-08328e00-8579-11eb-9186-6b4ebeef7fe8.png">
이런차이?

2021-03-15 01:27 UTC, seunghwako commented on pages/signup.tsx
> +  height: 48px;
아래 마진도 차이나고!

2021-03-15 01:41 UTC, ndaemy commented on pages/signup.tsx
> +  height: 48px;
width height text-align 세개만 뺀 거 맞지?

2021-03-15 01:42 UTC, seunghwako commented on pages/signup.tsx
> +  height: 48px;
네~

2021-03-15 01:50 UTC, ndaemy commented on pages/signup.tsx
> +  height: 48px;
아 두줄이라 그렇구나
다른덴 이렇게 되어있는거 없지?

2021-03-15 01:51 UTC, seunghwako commented on pages/signup.tsx
> +  height: 48px;
예압~

2021-03-15 01:53 UTC, ndaemy commented on pages/signup.tsx
> +  height: 48px;
그럼 패스~

2021-03-16 04:23 UTC, ndaemy commented on pages/signup.tsx
> +                value={selectedPosition}
이것도 formik에 넣을 수는 없나?

2021-03-16 04:23 UTC, ndaemy commented on pages/signup.tsx
> +                value={selectedPosition}
위에 세개도 포함해서

2021-03-16 04:24 UTC, seunghwako commented on pages/signup.tsx
> +                value={selectedPosition}
value?

2021-03-16 04:36 UTC, ndaemy commented on pages/signup.tsx
> +                value={selectedPosition}
ㅇㅇ

2021-03-16 13:52 UTC, ndaemy commented on pages/signup.tsx
> +  background-origin: content-box;
테스트

2021-03-18 15:44 UTC, merged